# Renders the "Peridot" title in the Neuton font as half-block coverage data,
# emitted as src/wordmark.js. Each terminal cell encodes two vertical pixels
# ('▀' with fg=top / bg=bottom); src/logo.js colors them with the active
# theme's gradient, giving a smooth antialiased serif wordmark in any theme.
import sys
from PIL import Image, ImageFont, ImageDraw

font_path, out_path = sys.argv[1], sys.argv[2]
TEXT = "Peridot"
COLS = 72  # character columns of the final art

font = ImageFont.truetype(font_path, 400)
bbox = font.getbbox(TEXT)
w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
img = Image.new("L", (w + 80, h + 80), 0)
ImageDraw.Draw(img).text((40 - bbox[0], 40 - bbox[1]), TEXT, font=font, fill=255)
img = img.crop(img.getbbox())

# Terminal cell ~1:2 → half-block subpixels are square.
grid_w = COLS
grid_h = max(2, round(img.height / img.width * COLS))
if grid_h % 2:
    grid_h += 1
img = img.resize((grid_w, grid_h), Image.LANCZOS)
px = img.load()

# Each cell is 4 hex digits: top-pixel coverage, then bottom-pixel coverage (00-ff).
rows = []
for row in range(grid_h // 2):
    rows.append("".join(f"{px[x, row * 2]:02x}{px[x, row * 2 + 1]:02x}" for x in range(grid_w)))

with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/gen-wordmark.py — Peridot title in the Neuton font.\n")
    f.write("// Regenerate: python scripts/gen-wordmark.py assets/Neuton-Regular.ttf src/wordmark.js\n")
    f.write("// Half-block cells, 4 hex digits each: top then bottom pixel coverage.\n")
    f.write(f"export const WORDMARK = {{\n  cols: {grid_w},\n  rows: [\n")
    f.write("".join(f"    '{r}',\n" for r in rows))
    f.write("  ],\n};\n")
print(f"wrote {out_path}: {len(rows)} rows x {grid_w} cols")
