# Renders the "Peridot" title in the Neuton font into ANSI half-block art,
# emitted as src/wordmark.js. Each terminal cell encodes two vertical pixels
# ('▀' with fg=top / bg=bottom), giving a smooth antialiased serif wordmark.
import sys
from PIL import Image, ImageFont, ImageDraw

font_path, out_path = sys.argv[1], sys.argv[2]
TEXT = "Peridot"
COLS = 72  # character columns of the final art

font = ImageFont.truetype(font_path, 400)
bbox = font.getbbox(TEXT)
w, h = bbox[2] - bbox[0], bbox[3] - bbox[1]
img = Image.new("L", (w + 80, h + 80), 0)
ImageDraw.Draw(img).text((40 - bbox[0], 40 - bbox[1]), TEXT, font=font, fill=255)
img = img.crop(img.getbbox())

# Terminal cell ~1:2 → half-block subpixels are square.
grid_w = COLS
grid_h = max(2, round(img.height / img.width * COLS))
if grid_h % 2:
    grid_h += 1
img = img.resize((grid_w, grid_h), Image.LANCZOS)
px = img.load()

# horizontal gradient: chartreuse (204,255,0) → neon peridot (128,255,0)
def color(x, cov):
    t = x / max(grid_w - 1, 1)
    r = round((204 + (128 - 204) * t) * cov)
    g = round(255 * cov)
    b = 0
    return r, g, b

LO = 0.06
lines = []
for row in range(grid_h // 2):
    out = []
    for x in range(grid_w):
        top = px[x, row * 2] / 255
        bot = px[x, row * 2 + 1] / 255
        if top < LO and bot < LO:
            out.append(" ")
            continue
        tr, tg, tb = color(x, max(top, LO if top >= LO else 0))
        br, bg_, bb = color(x, bot if bot >= LO else 0)
        out.append(f"\x1b[38;2;{tr};{tg};{tb}m\x1b[48;2;{br};{bg_};{bb}m▀\x1b[0m")
    lines.append("".join(out).rstrip())

js_lines = ",\n".join(
    "  " + '"' + l.replace("\\", "\\\\").replace('"', '\\"').replace("\x1b", "\\u001b") + '"'
    for l in lines
)
with open(out_path, "w", encoding="utf-8") as f:
    f.write("// Generated by scripts/gen-wordmark.py — Peridot title in the Neuton font.\n")
    f.write("// Regenerate: python scripts/gen-wordmark.py <neuton.ttf> src/wordmark.js\n")
    f.write("export const WORDMARK = [\n" + js_lines + "\n];\n")
print(f"wrote {out_path}: {len(lines)} rows x {grid_w} cols")
