import { C, gradientBlock, paint, DIM, currentTheme } from './theme.js';

// Glowing infinity loop — the peridot structure.
const INFINITY = [
  '                    .:oOOo:.    .:oOOo:.  ',
  "                   oO'    'Oo..oO'    'Oo ",
  '                  O:        :OO:        :O',
  '                  O:        :OO:        :O',
  "                   Oo.    .oO''Oo.    .oO ",
  "                    ':oOOo:'    ':oOOo:'  ",
];

// Fallback block wordmark, used only if the generated Neuton art is missing.
const BLOCK_WORDMARK = [
  ' ██████╗ ███████╗ ██████╗  ██╗ ██████╗   ██████╗  ████████╗',
  ' ██╔══██╗██╔════╝ ██╔══██╗ ██║ ██╔══██╗ ██╔═══██╗ ╚══██╔══╝',
  ' ██████╔╝█████╗   ██████╔╝ ██║ ██║  ██║ ██║   ██║    ██║   ',
  ' ██╔═══╝ ██╔══╝   ██╔══██╗ ██║ ██║  ██║ ██║   ██║    ██║   ',
  ' ██║     ███████╗ ██║  ██║ ██║ ██████╔╝ ╚██████╔╝    ██║   ',
  ' ╚═╝     ╚══════╝ ╚═╝  ╚═╝ ╚═╝ ╚═════╝   ╚═════╝     ╚═╝   ',
];

// Neuton-font wordmark coverage, generated by scripts/gen-wordmark.py.
let NEUTON = null;
try {
  ({ WORDMARK: NEUTON } = await import('./wordmark.js'));
} catch { /* fall back to block letters */ }

const LO = 0.06 * 255; // coverage below this is background

// Color the wordmark with the active theme: highlight → accent, left to right.
// Each cell is '▀' with fg = top pixel, bg = bottom pixel, scaled by coverage.
function neutonArt() {
  const { cols, rows } = NEUTON;
  const n = Math.max(cols - 1, 1);
  const shade = (x, cov) => [0, 1, 2].map((i) =>
    Math.round((C.chart[i] + (C.neon[i] - C.chart[i]) * (x / n)) * (cov / 255))).join(';');
  return rows.map((hex) => {
    let line = '';
    for (let x = 0; x < cols; x++) {
      const top = parseInt(hex.substr(x * 4, 2), 16);
      const bot = parseInt(hex.substr(x * 4 + 2, 2), 16);
      if (top < LO && bot < LO) { line += ' '; continue; }
      line += `\x1b[38;2;${shade(x, top)}m\x1b[48;2;${shade(x, bot >= LO ? bot : 0)}m▀\x1b[0m`;
    }
    return line.trimEnd();
  });
}

const artCache = new Map(); // theme id → rendered wordmark lines

export function logo() {
  const inf = gradientBlock(INFINITY, C.deep, C.green, DIM);
  let word;
  if (NEUTON) {
    const id = currentTheme().id;
    if (!artCache.has(id)) artCache.set(id, neutonArt());
    word = artCache.get(id).map((l) => ' ' + l);
  } else {
    word = gradientBlock(BLOCK_WORDMARK, C.chart, C.neon);
  }
  return [...inf, ...word].join('\n');
}

export function smallMark() {
  return paint('◈ peridot', C.neon);
}
