// Peridot theming — 24-bit ANSI on pitch black. The palettes live in
// src/themes.js (generated by native/rust/peridot-themes); `C` holds the active
// one and is updated in place, so every paint() picks up a theme switch.
import { THEMES } from './themes.js';

export { THEMES };

export const RESET = '\x1b[0m';
export const BOLD = '\x1b[1m';
export const DIM = '\x1b[2m';
export const ITALIC = '\x1b[3m';
export const UNDER = '\x1b[4m';
export const HIDE_CURSOR = '\x1b[?25l';
export const SHOW_CURSOR = '\x1b[?25h';

// Roles: neon (signature accent) · chart (highlight) · lime · green (primary) ·
// mid · deep · moss (secondary text) · dimg (dim lines/hints) · gray (tertiary) ·
// white (body text) · red (errors) · yellow (warnings) · bar (header/footer bg)
export const C = { ...THEMES[0].palette };

let current = THEMES[0];
export const currentTheme = () => current;

const slug = (s) => String(s || '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

// Find a theme by id, name, or an unambiguous prefix/fragment ("nyc", "seattle").
export function findTheme(query) {
  const q = slug(query);
  if (!q) return null;
  const exact = THEMES.find((t) => t.id === q);
  if (exact) return exact;
  for (const test of [(t) => t.id.startsWith(q), (t) => t.id.includes(q)]) {
    const hits = THEMES.filter(test);
    if (hits.length === 1) return hits[0];
    if (hits.length > 1) return null;
  }
  return null;
}

// Switch the active palette (unknown ids fall back to Peridot). Returns the theme.
export function applyTheme(id) {
  current = findTheme(id) || THEMES[0];
  Object.assign(C, current.palette);
  return current;
}

// A row of colored squares previewing a theme's palette.
export const swatch = (theme) => ['chart', 'neon', 'lime', 'green', 'mid', 'deep', 'dimg']
  .map((r) => fg(theme.palette[r]) + '■').join('') + RESET;

export const fg = ([r, g, b]) => `\x1b[38;2;${r};${g};${b}m`;

export const paint = (text, color, ...styles) => styles.join('') + fg(color) + text + RESET;

export const neon = (t) => paint(t, C.neon);
export const nb = (t) => paint(t, C.neon, BOLD);
export const soft = (t) => paint(t, C.moss);
export const dim = (t) => paint(t, C.dimg);
export const grey = (t) => paint(t, C.gray);
export const white = (t) => paint(t, C.white);
export const warn = (t) => paint(t, C.yellow);
export const err = (t) => paint(t, C.red);

const lerp = (a, b, t) => Math.round(a + (b - a) * t);

// Horizontal per-character gradient.
export function gradient(text, from, to, styles = '') {
  const chars = [...text];
  const n = Math.max(chars.length - 1, 1);
  let out = styles;
  for (let i = 0; i < chars.length; i++) {
    const t = i / n;
    if (chars[i] === ' ') { out += ' '; continue; }
    out += fg([lerp(from[0], to[0], t), lerp(from[1], to[1], t), lerp(from[2], to[2], t)]) + chars[i];
  }
  return out + RESET;
}

// Vertical gradient across an array of lines.
export function gradientBlock(lines, from, to, styles = '') {
  const n = Math.max(lines.length - 1, 1);
  return lines.map((line, i) => {
    const t = i / n;
    const c = [lerp(from[0], to[0], t), lerp(from[1], to[1], t), lerp(from[2], to[2], t)];
    return styles + fg(c) + line + RESET;
  });
}

export const cols = () => process.stdout.columns || 100;

export function rule(width = cols() - 2, color = C.dimg) {
  return paint('─'.repeat(Math.max(width, 10)), color);
}

// Left text + right text pushed to the edge.
export function spread(left, right, width = cols()) {
  const strip = (s) => s.replace(/\x1b\[[0-9;]*m/g, '');
  const pad = Math.max(width - strip(left).length - strip(right).length - 1, 1);
  return left + ' '.repeat(pad) + right;
}

export const stripAnsi = (s) => s.replace(/\x1b\[[0-9;]*m/g, '');
